version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres
    environment:
      POSTGRES_DB: postgres_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
